/*
    Defines a class for representing the Stewart platform. Supports calculation
    of motor angles required to achieve a desired platform pose. 

    Also defines a PlatformPose struct to represent this pose. 
*/

#ifndef STEWARTPLATFORM_H
#define STEWARTPLATFORM_H

#include "servoMotor.hpp"

#include <array>
#include <Eigen/Dense>

#define NUM_SERVOS 6

using Eigen::Vector3f;
using Eigen::Quaternionf;

struct PlatformPose
{
    /*  Position of the platform origin relative to the base origin.
        Platform origin: centre of platform at lowest platform height. */
    Vector3f position;          

    /*  Orientation of the platform relative to the base. */
    Quaternionf orientation; 
};

class StewartPlatform
{
    protected: 
        // Platform geometry 
        float lower_arm_length;                             // in mm     
        float upper_arm_length;                             // in mm      
        std::array<float, NUM_SERVOS> servo_angular_pos;    // Fixed angle of servo horns relative to the horizontal when viewed top-down, in radians
        std::array<Vector3f, NUM_SERVOS> base_anchors;      // Vector positions of the arm attachment points on the base relative to a centered origin, in mm
        std::array<Vector3f, NUM_SERVOS> platform_anchors;  // Platform attachment points, in mm

        // Latest platform pose target 
        PlatformPose platform_pose_target; 

        // The true pose of the platform per the position of the servo motors
        PlatformPose platform_pose;

        // Required servo angles for the latest platform pose target   
        std::array<float, NUM_SERVOS> servo_targets;
        
        // The Stewart platform servo motors
        std::array<ServoMotor, NUM_SERVOS> servos;

        // Hard limits on the max and min angle of each servo motor
        std::array<float, NUM_SERVOS> upper_servo_limits;
        std::array<float, NUM_SERVOS> lower_servo_limits;

        // Calculate the required servo angles to achieve the latest platform pose.
        // Implements the inverse kinematics of the Stewart platform. 
        bool computeServoTargets(bool print_errors);
    
    public: 
        StewartPlatform();
        ~StewartPlatform();

        // Move the platform to a target pose 
        bool moveTo(PlatformPose* target_pose);

        // Returns an array of the servo motor angles required to achieve the 
        // last target platform pose set with moveTo()
        const std::array<float, NUM_SERVOS>& getServoTargets() const;

        // Returns the current pose of the platform  
        const PlatformPose& getPlatformPose() const;

        // Calculate the position of the platform using the true motor angles. 
        // Implements the forward kinematics of the Stewart platform. 
        bool computePlatformPose();
};


// A class for analysing the workspace of the Stewart platform
class StewartPlatformAnalyser : public StewartPlatform
{
    private: 
        // Saves the point cloud generated by generatePointCloud to a csv file
        void savePointCloud(std::vector<PlatformPose>& point_cloud, std::string file_path);

        // Used by generatePointCloud to find valid platform poses
        bool searchAcrossOrientations();
    
    public: 
        // Generates a point cloud of possible platform positions
        void generatePointCloud(std::string file_path);
};

#endif