/*
Constructs and decodes messages of the UART_msg_t format specified in
uartInterface.hpp.
*/

#ifndef OBC_MESSAGE_HANDLER_H
#define OBC_MESSAGE_HANDLER_H

#include "uartInterface.hpp"

#include <cstdint>
#include <deque>
#include <queue>
#include <vector>
#include <string>

// --- Message IDs -------------------------------------------------------------

// Changes to message ids: 
//      one ack for all messages 0x68
//      transfer complete id: 0x70
//      packet id: 0x69
//      file info/header 0x66

// Unified acknowledgement (payload[0] = ID of the message being acknowledged)
#define PYLD_ACK_ID 0x68

// Experiment start / stop
#define PYLD_START_ID   0xA0
#define PYLD_STOP_ID    0xA1

// Debug mode
#define PYLD_ENTER_DEBUG_ID 0xA2

// File transfer - used for nominal & debug mode results transfer and for experiment settings file
#define PYLD_REQUEST_TRANSFER_ID    0xA4
#define PYLD_TRANSFER_HEADER_ID     0x66
#define PYLD_PACKET_ID              0x69
#define PYLD_TRANSFER_COMPLETE_ID   0x70

#define ACK_TIMEOUT 1000 // ms, time before a new message is sent because an acknowledge was not received

class ObcMessageHandler
{
    private:
        // For reading and writing messages to the UART port
        UartInterface uart_interface;

        // Last message matched by checkMessage(), available for payload reading (e.g. checkHeader)
        UART_msg_t last_message_read;

        // Incoming message queue - populated by drainUart(), consumed by checkMessage() and checkPacket()
        std::deque<UART_msg_t> receive_queue;

        // Messages to transmit - populated by serialiseResults()
        std::queue<UART_msg_t> transmit_queue;
        UART_msg_t last_msg_buffer; // saves the last message sent in case it needs to be resent
        UART_msg_t results_header;  // tells the OBC how many payload packets to expect

        // File receive buffer - populated by checkPacket(), consumed by deserialise()
        std::vector<UART_msg_t> file_receive_buffer;
        uint16_t num_expected_msgs; // set from the transfer header
        uint16_t msg_counter;       // number of file packets received so far

    public:
        ObcMessageHandler();
        ~ObcMessageHandler();

        // Drain all available UART messages into the receive queue, dropping bad-CRC messages.
        // Must be called once per state machine cycle before any checkMessage or checkPacket calls.
        void drainUart();

        // Transmit an ID-only message with the given message ID
        bool transmit(uint8_t id);

        // Transmit a unified ACK for the given message ID
        bool transmitAck(uint8_t acked_id);

        // Check for a message with the given ID in the receive queue.
        // Populates last_message_read on match.
        bool checkMessage(uint8_t id);

        // Check for a unified ACK whose payload identifies the given message ID
        bool checkAck(uint8_t acked_id);

        // Reads the header sent by the OBC and sets the number of messages expected to receive
        bool checkHeader();

        // Check for the next expected file packet, validate its sequence index,
        // and append to the file receive buffer on success
        bool checkPacket();

        // Returns true when all expected file packets have been received
        bool isReceiveComplete();

        // Reset the file receive buffer and packet counter between transfers
        void clearFileBuffer();

        // Deserialise the received file packets into:
        //   trajectory_path: 150-row CSV of p_x,p_y,p_z,roll,pitch,yaw (angles in degrees)
        //   settings_path:   scalar settings CSV (frame_rate, threshold, exposure, satellite attitude)
        bool deserialise(std::string trajectory_path, std::string settings_path);

        // Transmit the results transfer header
        bool transmitHeader();

        // Transmit the next results packet from the transmit queue
        bool transmitResultsPacket();

        // Retransmit the last results packet
        bool transmitLastResultsPacket();

        // Returns true when the transmit queue is empty
        bool isTransmitQueueEmpty();

        // Reads the csv results file generated by an experiment run and populates
        // the transmit message queue
        bool serialiseResults(std::string file_path);

        // Reads the jpeg file generated in the debug state and populates the
        // transmit message queue
        bool serialiseDebugResults(std::string file_path);
};

#endif
