/*
Constructs and decodes messages of the UART_msg_t format specified in
uartInterface.hpp.
*/

#ifndef OBC_MESSAGE_HANDLER_H
#define OBC_MESSAGE_HANDLER_H

#include "uartInterface.hpp"

#include <cstdint>
#include <deque>
#include <queue>
#include <vector>
#include <string>

// --- Message IDs -------------------------------------------------------------
// Experiment start / stop
#define PYLD_START_ID       0xA0
#define PYLD_START_ACK_ID   0xA1
#define PYLD_STOP_ID        0xA2
#define PYLD_STOP_ACK_ID    0xA3

// File transfer - used for nominal & debug mode results transfer and for experiment settings file
#define PYLD_REQUEST_TRANSFER_ID        0xA4
#define PYLD_TRANSFER_ACK_ID            0xA5
#define PYLD_TRANSFER_HEADER_ID         0xA6
#define PYLD_HEADER_ACK_ID              0xA7
#define PYLD_PACKET_ID                  0xA8
#define PYLD_PACKET_ACK_ID              0xA9
#define PYLD_TRANSFER_COMPLETE_ID       0xAA
#define PYLD_TRANSFER_COMPLETE_ACK_ID   0xAB

// Debug mode
#define PYLD_ENTER_DEBUG_ID 0xAC
#define PYLD_DEBUG_ACK_ID   0xAD

#define ACK_TIMEOUT 1000 // ms, time before a new message is sent because an acknowledge was not received

class ObcMessageHandler
{
    private:
        // For reading and writing messages to the UART port
        UartInterface uart_interface;

        // Last message matched by checkMessage(), available for payload reading (e.g. checkHeader)
        UART_msg_t last_message_read;

        // Incoming message queue - populated by drainUart(), consumed by checkMessage() and checkPacket()
        std::deque<UART_msg_t> receive_queue;

        // Messages to transmit - populated by serialiseResults()
        std::queue<UART_msg_t> transmit_queue;
        UART_msg_t last_msg_buffer; // saves the last message sent in case it needs to be resent
        UART_msg_t results_header;  // tells the OBC how many payload packets to expect

        // File receive buffer - populated by checkPacket(), consumed by deserialise()
        std::vector<UART_msg_t> file_receive_buffer;
        uint16_t num_expected_msgs; // set from the transfer header
        uint16_t msg_counter;       // number of file packets received so far

    public:
        ObcMessageHandler();
        ~ObcMessageHandler();

        // Drain all available UART messages into the receive queue, dropping bad-CRC messages.
        // Must be called once per state machine cycle before any checkMessage or checkPacket calls.
        void drainUart();

        // Transmit an ID-only message with the given message ID
        bool transmit(uint8_t id);

        // Check for a message with the given ID in the receive queue.
        // Populates last_message_read on match.
        bool checkMessage(uint8_t id);

        // Reads the header sent by the OBC and sets the number of messages expected to receive
        bool checkHeader();

        // Check for the next expected file packet, validate its sequence index,
        // and append to the file receive buffer on success
        bool checkPacket();

        // Returns true when all expected file packets have been received
        bool isReceiveComplete();

        // Reset the file receive buffer and packet counter between transfers
        void clearFileBuffer();

        // Deserialise the received file packets into:
        //   trajectory_path: 150-row CSV of p_x,p_y,p_z,roll,pitch,yaw (angles in degrees)
        //   settings_path:   scalar settings CSV (frame_rate, threshold, exposure, satellite attitude)
        bool deserialise(std::string trajectory_path, std::string settings_path);

        // Transmit the results transfer header
        bool transmitHeader();

        // Transmit the next results packet from the transmit queue
        bool transmitResultsPacket();

        // Retransmit the last results packet
        bool transmitLastResultsPacket();

        // Returns true when the transmit queue is empty
        bool isTransmitQueueEmpty();

        // Reads the csv results file generated by an experiment run and populates
        // the transmit message queue
        bool serialiseResults(std::string file_path);

        // Reads the jpeg file generated in the debug state and populates the
        // transmit message queue
        bool serialiseDebugResults(std::string file_path);
};

#endif
