/*
Constructs and decodes messages of the UART_msg_t format specified in 
uartInterface.hpp. 
*/

#ifndef OBC_MESSAGE_HANDLER_H
#define OBC_MESSAGE_HANDLER_H

#include "uartInterface.hpp"

#include <cstdint>
#include <queue>
#include <string>

// --- Message IDs -------------------------------------------------------------
// Experiment start / stop 
#define PYLD_START_ID       0xA0
#define PYLD_START_ACK_ID   0xA1
#define PYLD_STOP_ID        0xA2
#define PYLD_STOP_ACK_ID    0xA3

// File transfer - used for nominal & debug mode results transfer and for experiment settings file
#define PYLD_REQUEST_TRANSFER_ID        0xA4
#define PYLD_TRANSFER_ACK_ID            0xA5
#define PYLD_TRANSFER_HEADER_ID         0xA6
#define PYLD_HEADER_ACK_ID              0xA7
#define PYLD_PACKET_ID                  0xA8
#define PYLD_PACKET_ACK_ID              0xA9
#define PYLD_TRANSFER_COMPLETE_ID       0xAA
#define PYLD_TRANSFER_COMPLETE_ACK_ID   0xAB

// Debug mode
#define PYLD_ENTER_DEBUG_ID 0xAC
#define PYLD_DEBUG_ACK_ID   0xAD

#define ACK_TIMEOUT 1000 // ms, time before a new message is sent because an acknowledge was not received

class ObcMessageHandler
{
    private: 
        // For reading and writing messages to the UART port
        UartInterface uart_interface;

        // Received single messages
        UART_msg_t last_message_read;
        bool message_is_stored;
        
        // Messages to transmit - populated by serialiseResults()
        std::queue<UART_msg_t> transmit_queue;
        UART_msg_t last_msg_buffer; // saves the last message sent in case it needs to be resent 
        UART_msg_t results_header;  // tells the OBC how many payload packets to expect

        // Messages received from the OBC specifying an experiment settings file
        std::queue<UART_msg_t> receive_queue;
        uint16_t num_expected_msgs;
        uint16_t msg_counter; 

        // Formats and transmits UART messages with a single payload byte equal
        // to the message ID. 
        bool transmitIdOnlyMessage(uint8_t id);
        
        // Check for a message sent over UART and store in last_message_read.
        // Flag when a message has been received in last_message_received.
        // Overwrites any message already stored in last_message_read. 
        bool getMessage();

        // Checks if a message with the given id is stored in last_message_read 
        // or if it can be read from the UART terminal 
        bool checkForMessage(uint8_t id);

    public: 
        ObcMessageHandler();
        ~ObcMessageHandler();

        // Experiment start / stop messages
        bool transmitStartAck();
        bool transmitStopAck();
        bool checkStartMsg();
        bool checkStopMsg();

        // Messages for Payload -> OBC comms
        bool transmitTransferRequest();
        bool transmitHeader();
        bool transmitResultsPacket(); // for transferring each message of the transmit queue
        bool transmitLastResultsPacket(); // for re-trying the last message 
        bool transmitTransferComplete();
        bool checkTransferAck();
        bool checkHeaderAck();
        bool checkPacketAck();
        bool checkTransferCompleteAck();

        // Messages for OBC -> Payload comms
        bool transmitTransferAck();
        bool transmitHeaderAck();
        bool transmitPacketAck();
        bool checkTransferRequest();
        bool checkHeader();
        bool checkPacket();
        bool checkTransferComplete();

        // Debug mode messages
        bool transmitDebugAck();
        bool checkEnterDebugMsg();

        // Reads the csv results file generated by an experiment run and populates
        // the transmit message queue
        bool serialiseResults(std::string file_path);

        // Reads the jpeg file generated in the debug state and populates the 
        // transmit message queue
        bool serialiseDebugResults(std::string file_path);

        // Returns whether the transmit queue is empty
        bool isTransmitQueueEmpty();
};

#endif 